services:
  freeswitch:
    build:
      context: ./freeswitch-build
      dockerfile: Dockerfile
    platform: linux/arm64
    container_name: voip-freeswitch
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "5080:5080/tcp"
      - "8021:8021/tcp"
      - "10000-10020:10000-10020/udp"
    volumes:
      - ./configs/freeswitch:/etc/freeswitch:ro
      - ./logs:/var/log/freeswitch
      - freeswitch_storage:/var/lib/freeswitch
    environment:
      - FREESWITCH_LOG_LEVEL=INFO
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - voip-network

  database:
    image: postgres:15-alpine
    platform: linux/arm64
    container_name: voip-postgres
    environment:
      POSTGRES_DB: freeswitch
      POSTGRES_USER: freeswitch
      POSTGRES_PASSWORD: freeswitch_mvp_password
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - voip-network

  adminer:
    image: adminer:latest
    platform: linux/arm64
    container_name: voip-adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: database
    depends_on:
      - database
    networks:
      - voip-network
    profiles:
      - dev

networks:
  voip-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  postgres_data:
  freeswitch_storage:
