services:
  freeswitch:
    build:
      context: .
      dockerfile: freeswitch-build/Dockerfile
    platform: linux/arm64
    container_name: voip-freeswitch
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "5080:5080/tcp"
      - "8021:8021/tcp"
      - "10000-10100:10000-10100/udp"
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep freeswitch | grep -v grep && netstat -tlnp | grep :5060 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./configs:/etc/freeswitch:rw
      - ./logs:/var/log/freeswitch:rw
      - freeswitch_storage:/var/lib/freeswitch:rw
      - freeswitch_run:/var/run/freeswitch:rw
    environment:
      - FREESWITCH_LOG_LEVEL=INFO
    restart: "no"
    stdin_open: true
    tty: true
    depends_on:
      - database
    networks:
      - voip-network

  database:
    image: postgres:15-alpine
    platform: linux/arm64
    container_name: voip-postgres
    environment:
      POSTGRES_DB: freeswitch
      POSTGRES_USER: freeswitch
      POSTGRES_PASSWORD: freeswitch_mvp_password
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - voip-network

  adminer:
    image: adminer:latest
    platform: linux/arm64
    container_name: voip-adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: database
    depends_on:
      - database
    networks:
      - voip-network
    profiles:
      - dev

networks:
  voip-network:
    driver: bridge

volumes:
  postgres_data:
  freeswitch_storage:
  freeswitch_run:
